include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_relative_imports: true
    prefer_const_constructors: true
    always_put_required_named_parameters_first: true
    constant_identifier_names: true
    unawaited_futures: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    sort_pub_dependencies: false
    sort_constructors_first: true
    omit_local_variable_types: true
    use_build_context_synchronously: false